### ISSUE TITLE
Is there anyway to see the result also in pixels unit?

### ISSUE THREAD

**Issue by callmehanu** [jeremychurch/type-scale#16]
Yep, **ems** are great for code and implementation, but in the design process, pixel is more useful!

**Comment by jeremychurch** [comment]
It's not something I'm planning to add, but you can use this spreadsheet to get px values based on the base size and scale:

[Type Scale - em _ px.xlsx](https://github.com/jeremychurch/type-scale/files/2237294/Type.Scale.-.em._.px.xlsx)

**Comment by callmehanu** [comment]
Thanks, @jeremychurch  
Nowadays, I am using the web inspector!

**Comment by jeremychurch** [comment]
Oh yeah the computed values there would work great as well.

**Comment by robsonsobral** [comment]
Hi!

To have the pixel values isn't helpful to developers, but it's to designers working on Photoshop.

Please, reconsider.

**Comment by jeremychurch** [comment]
Deployed px values today #21
