### ISSUE TITLE
A longer values table

### ISSUE THREAD

**Issue by robsonsobral** [jeremychurch/type-scale#19]
To have a table with more values, like [Modular Scale does](https://www.modularscale.com/?1&em&1.5) would be useful for designers working on Photoshop or Illustrator.

---

I'm sorry for bother you so much today, @jeremychurch . I talked a lot of time yesterday with the designer on my team.

**Comment by jeremychurch** [comment]
I added one more with the last round of updates, but I don't have any plans to add a larger table at this time, for now I would recommend using the modular scale site to get a list of more values.

**Comment by robsonsobral** [comment]
WOW! It really helps! Thank you! I'm trying to make designers and developers to work more closely and you helped a lot!
