### ISSUE TITLE
Nomenclature explanation

### ISSUE THREAD

**Issue by sujan-s** [jeremychurch/type-scale#25]
Hi, could you add a brief explanation about the nomenclature for the various scales like major, minor and augmented? I get that it has got something to do with music, but don’t really grasp the ideology behind it.

A short write-up on the site would be great. Doable?

**Comment by jeremychurch** [comment]
There are a lot of people who have written on this, and they do a better job than I could, so I will leave it to them, but I'll consider adding a link to one of them under the resources section.

Here are a few that you may want to look at:
- http://spencermortensen.com/articles/typographic-scale/
- https://medium.com/sketch-app-sources/exploring-responsive-type-scales-cf1da541be54 (this one does a good job of explaining which scales work in certain contexts; e.g. marketing vs software)
- https://alistapart.com/article/more-meaningful-typography
