### ISSUE TITLE
Generated CSS contains wrong font-family

### ISSUE THREAD

**Issue by grubersjoe** [jeremychurch/type-scale#31]
Hey there. Nice tool! 

I think I found a small bug: if you choose another Google Font the generated CSS still contains Poppins.

![grafik](https://user-images.githubusercontent.com/3109364/82193809-35c98f00-98f6-11ea-903e-e62c28943b43.png)

**Comment by helloshantanu** [comment]
Hi Johnathon, thats not actually a bug, the font poppins is actually for the elements on the left side of body, these elements display the size and pixels 

Eg: on the left of side of the "A visual  type scale", we see size as 3.052em and(54.93 px) and look at that font. 

Its Poppins, i hope you get it. 
The quick fix for you here is after copying css from here, you can change the body `font-family`  to font of your choice.

meanwhile i will try to fix that issue.

Thanks

**Comment by jeremychurch** [comment]
Correct, this is intentional, so header and body font can be unique and independent of the other. However, there are many times when only one font is needed for both, so I'll probably address that at some point. 

Closing this issue for now. Thanks for your input.

**Comment by jeremychurch** [comment]
@grubersjoe Hey. I just deployed an update (#33) that changes how things work, and fixes the url issue you noticed. The main font field now updates both the headers and body font, unless you manually select a body font. Probably how it should have worked to begin with. Thanks again for your feedback.

**Comment by grubersjoe** [comment]
Great, thank you!
